config/routes.rb
ContentManager::Engine.routes.draw do
  root 'views#index'

  resources :views, only: [:index, :show, :edit, :update] do
    resources :contents
  end
end

app/models/content_manager/content.rb
module ContentManager
  class Content < ActiveRecord::Base
    belongs_to :view
    serialize :data, JSON
  end
end

app/models/content_manager/view.rb
module ContentManager
  class View < ActiveRecord::Base
    has_many :contents

    def to_constant
      constant_name.classify.constantize
    end

    def name
      read_attribute(:name) || constant_name
    end
  end
end

app/controllers/content_manager/application_controller.rb
module ContentManager
  class ApplicationController < ::ApplicationController
    # Provide layout for all views unless none is given
    layout ContentManager.layout unless ContentManager.layout.nil?
    # auth the controllers unless no auth is provided
    before_action ContentManager.admin_auth_method unless ContentManager.admin_auth_method.nil?
  end
end

app/controllers/content_manager/contents_controller.rb
require_dependency "content_manager/application_controller"

module ContentManager
  class ContentsController < ApplicationController
    before_action :current_view
    before_action :current_content, only: [:show, :destroy, :edit, :update]

    def index
      @content = ContentsIndexContent.new(version: 0)
      @contents = current_view.contents
    end

    def show
    end

    def new
      @content = current_view.contents.new()
    end

    def create
      @content = current_view.contents.new(content_params)
      if @content.save
        redirect_to view_contents_path(current_view)
      else
        redirect_to :new, notice: "Content creation failed!"
      end
    end

    def destroy
      @content.destroy
      redirect_to view_contents_path(current_view)
    end

    def edit
    end

    def update
      if current_content.update(content_params)
        redirect_to view_content_path(current_view, current_content)
      else
        redirect_to edit_view_content_path(current_view, current_content), notice: "Failed to update Content"
      end
    end

    private

    def current_content
      @content ||= current_view.contents.find(params[:id])
    end

    def current_view
      @view ||= View.find(params[:view_id])
    end

    def content_params
      params.require(:content).permit(:version, data: current_view.to_constant.content_keys)
    end
  end
end

app/controllers/content_manager/view_controller.rb
require_dependency "content_manager/application_controller"

module ContentManager
  class ViewController < ApplicationController
    def index
      @content = ViewIndexContent.new(version: 0)
      @views = View.all
    end

    def show
      @content = ViewShowContent.new(version: 0)
      @view = View.find(params[:id])
    end

    def edit
      @view = View.find(params[:id])
    end

    def update
      @view = View.find(params[:id])
    end
  end
end

app/controllers/content_manager/views_controller.rb
require_dependency "content_manager/application_controller"

module ContentManager
  class ViewsController < ApplicationController
    def index
      # this is the ideal place for a presenter
      if ContentManager.show_internal_content
        @views = View.all
      else
        @views = View.where.not("constant_name LIKE 'ContentManager%'")
      end
    end

    def show
      @view = View.find(params[:id])
    end

    def edit
      @view = View.find(params[:id])
    end

    def update
      @view = View.find(params[:id])
      @view.update_attributes(view_params)
      if @view.valid?
        @view.save
        redirect_to :back
      else
        redirect_to :back, alert: 'Invalid View'
      end
    end

    private

    def view_params
      params.require(:view).permit(:active_template)
    end
  end
end

app/helpers/content_manager/application_helper.rb
# Rubies SimpleDelegator doesn't seem to work
# for this usecase? TODO: Explore more.
class Proxy
  def initialize(delegate, &block)
    @delegate = delegate
    yield self unless block.nil?
  end
  def method_missing(*args, &block)
    @delegate.send(*args, &block) 
  end
end

module ContentManager
  module ApplicationHelper
    # a helper to automatically figure out where to get you're content from
    def cm(key)
      content_instance.public_send(key.to_sym)
    end

    def content_view(view_name, &block)
      # scope a block to a content view via a proxy view
      template = block.binding.eval('self')
      proxy = Proxy.new(template) do |proxy|
        content = content_instance(view_name.to_s)

        template.instance_variables.each do |key|
          proxy.instance_variable_set(key, template.instance_variable_get(key))
        end
        proxy.define_singleton_method(:cm) do |key|
          content.public_send(key.to_sym)
        end
      end
      proxy.instance_eval(&block)
    end

    private

    def content_instance(name=nil)
      # Why not just use a function?
      content_class = ClassResolution.content_class(name || constant_name)

      #TODO:  defaults to verrsion 0, need to allow specifying default
      @content_instance = content_class.new(version: 0)
    end

    # the default for constants will be ControllerActionContent
    def constant_name
      # extend the controller api, this could probably be simpler
      "#{controller.controller_name}_#{controller.action_name}_content"
    end
  end
end

app/helpers/content_manager/content_helper.rb
module ContentManager
  module ContentHelper
  end
end

app/helpers/content_manager/view_helper.rb
module ContentManager
  module ViewHelper
  end
end

app/views/content_manager/content/index.html.erb
<h1><%= @view.name %></h1>
<h2>Content Keys</h2>
<% @view.to_constant.content_keys.each do |key| %>
  <span><%= key %> </span>
<% end %>
<h2>Content Versions</h2>
<% @contents.each do |c| %>
  <%= link_to c.version.to_s, view_content_path(@view, c) %>
<% end %>
<%= link_to 'New', new_view_content_path(@view) %>

app/views/content_manager/content/new.html.erb
<h1><%= @view.name %> Content</h1>
<h2>New Content</h2>

<%= form_for @content, url: { action: 'create' } do |f|  %>
  <div>
    <%= f.label :version do %>
      version:
      <%= f.text_field :version %>
    <% end %>
  </div>
  <div>
    <%= f.fields_for :data do |d|%>
      <% @view.to_constant.content_keys.each do |key| %>
        <%= d.label key do %>
          <%= key %>:
          <%= d.text_field key.to_sym %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%= f.submit 'Create' %>
<% end %>

app/views/content_manager/contents/_form.html.erb
<%= form_for [@view, @content] do |f|  %>
  <div>
    <%= f.label :version do %>
      version:
      <%= f.text_field :version %>
    <% end %>
  </div>

  <br>

  <fieldset>
    <div>
      <%= f.fields_for :data do |d|%>
        <% @view.to_constant.content_keys.each do |key| %>
          <div>
            <%= d.label key do %>
              <%= key %>:
              <%= d.text_area key.to_sym, value: @content.data[key.to_s], rows: 1, cols: 80 %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </fieldset>

  <br>

  <%= f.submit cm :form_submit %>
<% end %>

app/views/content_manager/contents/edit.html.erb
<h1><%= @view.name %></h1>
<h2><%= cm :update_title %></h2>

<%= render partial: 'form' %>

app/views/content_manager/contents/index.html.erb
<h1><%= @view.name %></h1>

<% if @view.to_constant.available_templates.size > 0 %>
  <%= form_for @view do |f|%>
    <%= f.label 'Active Template' do %>
      <%= f.select :active_template, @view.to_constant.available_templates || [] %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% end %>

<span><b><%= @content.keys_title %>:</b></span>

<% @view.to_constant.content_keys.each do |key| %>
  <span><%= key %> </span>
<% end %>
<hr>

<table>
  <thead>
    <tr>
      <th colspan="1"><h3><%= @content.versions_title %></h3></th>
      <th colspan="1"><%= link_to @content.new_button, new_view_content_path(@view) %></th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |c| %>
      <tr>
        <td><%= link_to c.version.to_s, view_content_path(@view, c) %></td>
        <td><%= link_to @content.destroy_button, view_content_path(@view, c), method: :delete %></td>
        <td><%= link_to @content.edit_button, edit_view_content_path(@view, c) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/content_manager/contents/new.html.erb
<h1><%= @view.name %></h1>
<h2><%= cm :new_title %></h2>

<%= render partial: 'form' %>

app/views/content_manager/contents/show.html.erb
<h1><%= @view.name %> Content</h1>
<span>version: <%= @content.version %></span>
<h2>Content Keys</h2>

<table border="0" cellspacing="5" cellpadding="5">
  <tr><th>Key</th><th>Value</th></tr>
<% @content.data.each do |key, value|%>
  <tr><td><%= key %></td><td><%= value %></td></tr>
<% end %>
</table>

app/views/content_manager/view/index.html.erb
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th><%= @content.view_name_title %></th></tr>
  <% @views.each do |v| %>
    <tr>
      <td><%= link_to v.name, view_content_index_path(v) %></td>
    </tr>
  <% end %>
</table>

app/views/content_manager/views/index.html.erb
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th><%= cm :view_name_title %></th></tr>
  <% @views.each do |v| %>
    <tr>
      <td><%= link_to v.name, view_contents_path(v) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/content_manager/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContentManager</title>
  <%= stylesheet_link_tag    "content_manager/application", media: "all" %>
  <%= javascript_include_tag "content_manager/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>